[package]
name = "rust_client"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.10.10"
solana-client = "1.10.10"
solana-program = "1.10.10"
serde = "1.0.137"
serde_json = "1.0.81"
chrono = "0.4.19"
sol-lock = { path = "../program" }